import Image from 'next/image'
import Link from 'next/link'
import { SiteNav } from '@/components/marketing/SiteNav'

const skyline = 'https://images.unsplash.com/photo-1652707228067-25672fa0b082?auto=format&fit=crop&w=1800&q=85'

const primary = 'inline-flex min-h-11 items-center justify-center rounded-radius-md bg-redesign-gold px-6 py-3 text-sm font-bold text-forest-deep shadow-redesign-cta-glow transition hover:-translate-y-0.5'
const secondary = 'inline-flex min-h-11 items-center justify-center rounded-radius-md border border-white/25 px-6 py-3 text-sm font-bold text-white transition hover:border-redesign-gold-dark/60'
const card = 'rounded-radius-lg border border-line-light bg-surface-light p-6 shadow-redesign-sm'

const services = [
  ['GCC Readiness', 'Check whether your resume is positioned for the Gulf market.', '/ats-scan', 'FREE'],
  ['ATS + Job Match', 'Compare your resume with the exact job description before applying.', '/ats-scan', 'LIVE'],
  ['Resume Optimization', 'Reframe your real experience for the role without inventing facts.', '/optimize', 'LIVE'],
  ['Career Profile', 'Create one trusted career profile to power future applications.', '/onboarding', 'LIVE'],
  ['Resume Library', 'Keep your resume versions and application documents organized.', '/dashboard/library', 'LIVE'],
  ['Cover Letter', 'Create a role-specific letter grounded in your actual experience.', '/cover-letter', 'LIVE'],
  ['Job Match', 'Understand strengths, gaps and fit for a target Gulf role.', '/job-match', 'LIVE'],
  ['Interview Preparation', 'Mock interviews and role-specific preparation are next.', '#coming-soon', 'COMING SOON'],
] as const

const painPoints = [
  ['01', 'Applying everywhere but hearing nothing', 'More applications cannot fix a resume that is generic or poorly aligned.'],
  ['02', 'Your CV is not positioned for the Gulf', 'Good experience can still be presented in the wrong context for GCC hiring.'],
  ['03', 'One resume for every job', 'Different roles need different evidence, keywords and priorities.'],
  ['04', 'You do not know what to fix', 'A clear diagnosis tells you where to spend your effort first.'],
  ['05', 'Generic AI applications', 'Polished text is not enough if it does not reflect your real career.'],
  ['06', 'Interview preparation comes too late', 'A stronger application is the first step toward a stronger interview.'],
] as const

const faqs = [
  ['Do I need an account for the first scan?', 'No. The free ATS/GCC scan can start without login.'],
  ['Can I check one resume against one specific job?', 'Yes. Add the job description and the platform can analyze the application against that target.'],
  ['Will the optimizer invent achievements?', 'The product is designed to keep generated resume content grounded in your Career Profile and real information.'],
  ['Which GCC markets are supported?', 'Saudi Arabia, UAE, Qatar, Oman, Kuwait and Bahrain are the current focus markets.'],
]

function Score({ title, value, note }: { title: string; value: string; note: string }) {
  return <div className="rounded-radius-lg border border-line-light bg-white/95 p-4 shadow-redesign-sm"><p className="text-[10px] font-bold tracking-[0.16em] text-ink-400">{title}</p><p className="mt-2 font-mono text-3xl font-bold text-forest">{value}<span className="text-sm">/100</span></p><p className="mt-1 text-xs text-ink-700">{note}</p></div>
}

function ResumeMockup() {
  return <div className="relative mx-auto w-full max-w-[650px]">
    <div className="absolute -inset-6 rounded-[2rem] bg-redesign-gold/15 blur-3xl" />
    <div className="relative rounded-radius-xl border border-white/15 bg-forest-deep/95 p-3 shadow-redesign-xl">
      <div className="relative overflow-hidden rounded-radius-lg bg-surface-light p-5 sm:p-7">
        <Image src={skyline} alt="Gulf skyline" fill className="absolute inset-0 object-cover opacity-[0.06]" priority />
        <div className="relative">
          <div className="flex items-center justify-between border-b border-line-light pb-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-forest">GCC MENTOR</p><p className="mt-1 text-[11px] text-ink-400">Target application analysis</p></div><span className="rounded-full bg-forest-tint px-3 py-1 text-[10px] font-bold text-forest">LIVE CHECK</span></div>
          <div className="mt-5 grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
            <div className="rounded-radius-lg border border-line-light bg-white/95 p-5"><div className="flex items-start justify-between"><div><p className="font-serif text-xl text-ink-900">Ahmed Khan</p><p className="mt-1 text-xs font-semibold text-forest">Senior Project Manager · Dubai, UAE</p></div><span className="rounded bg-surface-2-light px-2 py-1 text-[9px] font-bold text-ink-400">CV.pdf</span></div><div className="mt-6 space-y-5"><div><p className="text-[9px] font-bold uppercase tracking-wider text-ink-400">Experience</p><div className="mt-2 space-y-2"><span className="block h-2 w-[96%] rounded bg-ink-200"/><span className="block h-2 w-[88%] rounded bg-ink-200"/><span className="block h-2 w-[72%] rounded bg-ink-200"/></div></div><div><p className="text-[9px] font-bold uppercase tracking-wider text-ink-400">Skills</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="rounded bg-forest-tint px-2 py-1 text-[9px] font-bold text-forest">PMP</span><span className="rounded bg-forest-tint px-2 py-1 text-[9px] font-bold text-forest">Agile</span><span className="rounded bg-forest-tint px-2 py-1 text-[9px] font-bold text-forest">SAP</span><span className="rounded bg-forest-tint px-2 py-1 text-[9px] font-bold text-forest">Leadership</span></div></div></div></div>
            <div className="space-y-3"><Score title="GCC READINESS" value="78" note="Market positioning"/><Score title="ATS SCORE" value="92" note="For this job"/><Score title="JOB MATCH" value="88" note="Experience fit"/></div>
          </div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-radius-lg border border-redesign-gold/40 bg-redesign-gold-tint p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-gold-text">3 priority improvements</p><p className="mt-2 text-sm font-semibold text-ink-900">Keywords · impact language · GCC positioning</p></div><div className="rounded-radius-lg border border-forest/15 bg-forest-tint p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-forest">Next action</p><p className="mt-2 text-sm font-semibold text-ink-900">Optimize this resume for the target job</p></div></div>
        </div>
      </div>
    </div>
  </div>
}

export default function Home() {
  return <div className="min-h-screen overflow-x-clip bg-bg text-ink-900"><SiteNav/><main>
    <section className="relative overflow-hidden bg-forest-deep text-white"><Image src={skyline} alt="Dubai skyline at dusk" fill priority className="absolute inset-0 object-cover opacity-20"/><div className="absolute inset-0 bg-gradient-to-r from-forest-deep via-forest-deep/95 to-forest-deep/65"/><div className="relative mx-auto grid max-w-[1280px] gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-12 lg:py-24"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text-dark">Built for GCC job seekers</p><h1 className="mt-5 max-w-3xl font-serif text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">Stop applying blindly. <span className="text-gold-text-dark">Know why your resume is not getting noticed.</span></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/75 sm:text-xl">Upload your resume, add the job you want, and see your <strong className="text-white">GCC Readiness, ATS Score and Job Match</strong> before you spend another application.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/ats-scan" className={primary}>Check my GCC readiness — free</Link><Link href="/onboarding" className={secondary}>Build my Career Profile</Link></div><p className="mt-4 text-xs text-white/50">No login required for the first scan · PDF / Word supported · Saudi Arabia · UAE · Qatar · Kuwait · Oman · Bahrain</p></div><ResumeMockup/></div></section>

    <section id="problem" className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="max-w-3xl"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text">The pain point</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">You do not need more applications. You need a better application strategy.</h2><p className="mt-5 text-lg leading-relaxed text-ink-700">If you have experience but still struggle to land a well-paid GCC role, GCC MENTOR helps you understand what is weak, what matches and what to improve first.</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{painPoints.map(([n,t,d])=><div key={n} className={card}><span className="font-mono text-xs text-terra">{n}</span><h3 className="mt-4 font-serif text-xl">{t}</h3><p className="mt-2 text-sm leading-relaxed text-ink-700">{d}</p></div>)}</div></section>

    <section className="border-y border-line-dark bg-forest-deep text-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-12 lg:py-24"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text-dark">How it works</p><h2 className="mt-4 max-w-3xl font-serif text-4xl leading-tight sm:text-5xl">From resume to job-specific application in four steps.</h2><div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{[['01','Upload your resume','PDF, Word or pasted text.'],['02','Add the job description','Tell us exactly what you are targeting.'],['03','Get your scores','GCC Readiness, ATS and Job Match.'],['04','Fix what matters','Optimize the resume and create the cover letter.']].map(([n,t,d])=><div key={n} className="rounded-radius-lg border border-white/15 bg-white/5 p-6"><span className="font-mono text-xs text-gold-text-dark">{n}</span><h3 className="mt-8 font-serif text-2xl">{t}</h3><p className="mt-2 text-sm text-white/65">{d}</p></div>)}</div><Link href="/ats-scan" className={`${primary} mt-10`}>Start free</Link></div></section>

    <section className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text">Why the scores matter</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Your resume should be checked for the market, the system and the job.</h2><div className="mt-8 space-y-3"><div className={card}><h3 className="font-serif text-xl">GCC Readiness</h3><p className="mt-2 text-sm text-ink-700">Are your structure, clarity and Gulf-market positioning ready?</p></div><div className={card}><h3 className="font-serif text-xl">ATS Score</h3><p className="mt-2 text-sm text-ink-700">Is your resume readable and aligned for the application?</p></div><div className="rounded-radius-lg border border-redesign-gold/50 bg-redesign-gold-tint p-6"><h3 className="font-serif text-xl">Job Match</h3><p className="mt-2 text-sm text-ink-700">How closely does your actual experience match this particular job description?</p></div></div></div><ResumeMockup/></div></section>

    <section id="services" className="border-y border-line-light bg-surface-2-light"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text">The platform</p><h2 className="mt-4 max-w-3xl font-serif text-4xl leading-tight sm:text-5xl">All the tools needed to build a stronger GCC job application.</h2><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(([t,d,h,s])=><div key={t} className="flex min-h-[230px] flex-col rounded-radius-lg border border-line-light bg-surface-light p-6"><span className="w-fit rounded-full border border-line-light px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-ink-400">{s}</span><h3 className="mt-6 font-serif text-2xl">{t}</h3><p className="mt-2 text-sm leading-relaxed text-ink-700">{d}</p>{h.startsWith('/')?<Link href={h} className="mt-auto pt-6 text-sm font-bold text-forest underline underline-offset-4">Explore {t} →</Link>:<a href={h} className="mt-auto pt-6 text-sm font-bold text-ink-400">See what is next →</a>}</div>)}</div></div></section>

    <section id="optimization" className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="grid gap-10 lg:grid-cols-2 lg:items-center"><div className="rounded-radius-xl bg-forest-deep p-6 shadow-redesign-lg"><div className="rounded-radius-lg bg-white p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-ink-400">BEFORE</p><p className="mt-3 text-sm text-ink-700">Responsible for managing projects and coordinating teams.</p><div className="py-5 text-center text-2xl text-gold-text">↓</div><p className="text-[10px] font-bold uppercase tracking-wider text-gold-text">OPTIMIZED FOR TARGET ROLE</p><p className="mt-3 text-sm font-semibold leading-relaxed text-ink-900">Reframed to emphasize relevant delivery, leadership and project evidence already present in your Career Profile.</p><span className="mt-4 inline-flex rounded-full bg-forest-tint px-2.5 py-1 text-[9px] font-bold text-forest">GROUNDED IN YOUR FACTS</span></div></div><div><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text">Resume optimization</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Stronger positioning. Same truth.</h2><p className="mt-5 text-lg leading-relaxed text-ink-700">Optimize your resume for one target role while keeping your real employers, titles, dates, education, certifications and experience grounded.</p><Link href="/optimize" className={`${primary} mt-8`}>Optimize my resume</Link></div></div></section>

    <section className="border-y border-line-dark bg-forest-deep text-white"><div className="mx-auto max-w-[1280px] px-5 py-20 sm:px-8 lg:px-12 lg:py-24"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text-dark">One application journey</p><h2 className="mt-4 max-w-3xl font-serif text-4xl leading-tight sm:text-5xl">Check the fit → optimize → write the letter → apply.</h2><div className="mt-10 grid gap-3 md:grid-cols-3"><Link href="/job-match" className="rounded-radius-lg border border-white/15 bg-white/5 p-6"><span className="font-mono text-xs text-gold-text-dark">01</span><h3 className="mt-7 font-serif text-2xl">Job Match</h3><p className="mt-2 text-sm text-white/65">Understand fit before spending time applying.</p></Link><Link href="/cover-letter" className="rounded-radius-lg border border-white/15 bg-white/5 p-6"><span className="font-mono text-xs text-gold-text-dark">02</span><h3 className="mt-7 font-serif text-2xl">Cover Letter</h3><p className="mt-2 text-sm text-white/65">Connect your real story to the target employer.</p></Link><div className="rounded-radius-lg border border-white/15 bg-white/5 p-6"><span className="font-mono text-xs text-gold-text-dark">03</span><h3 className="mt-7 font-serif text-2xl">Interview</h3><p className="mt-2 text-sm text-white/65">Interview preparation is coming next.</p><span className="mt-5 inline-flex rounded-full border border-redesign-gold-dark/40 px-2.5 py-1 text-[10px] font-bold uppercase text-gold-text-dark">Coming soon</span></div></div></div></section>

    <section id="pricing" className="mx-auto max-w-[1100px] px-5 py-20 sm:px-8 lg:py-28"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text">Start here</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">See the problem before you pay to fix it.</h2><p className="mt-5 max-w-2xl text-lg text-ink-700">Start with the free readiness scan. If you need deeper tools, continue into your Career Profile and application workflow.</p><div className="mt-10 rounded-radius-xl border border-redesign-gold/50 bg-redesign-gold-tint p-8 sm:p-10"><p className="font-mono text-4xl font-bold text-forest">Free</p><h3 className="mt-3 font-serif text-3xl">GCC Readiness + ATS Scan</h3><p className="mt-3 max-w-2xl text-sm leading-relaxed text-ink-700">Upload your CV and optionally add the job description. Get a useful first diagnosis before deciding what to do next.</p><Link href="/ats-scan" className={`${primary} mt-7`}>Check my GCC readiness — free</Link></div></section>

    <section id="resources" className="border-t border-line-light bg-surface-2-light"><div className="mx-auto max-w-[900px] px-5 py-20 sm:px-8 lg:py-24"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text">FAQ</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Clear answers before you trust a career tool.</h2><div className="mt-10 divide-y divide-line-light rounded-radius-lg border border-line-light bg-surface-light px-6">{faqs.map(([q,a])=><details key={q} className="group py-5"><summary className="cursor-pointer list-none pr-8 font-bold">{q}<span className="float-right text-gold-text">＋</span></summary><p className="mt-3 text-sm leading-relaxed text-ink-700">{a}</p></details>)}</div></div></section>

    <section id="coming-soon" className="border-t border-line-dark bg-forest-deep text-center text-white"><div className="mx-auto max-w-[850px] px-5 py-20 sm:px-8 lg:py-24"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-gold-text-dark">Next</p><h2 className="mt-4 font-serif text-4xl sm:text-5xl">Interview preparation is coming.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-white/65">Mock interviews and role-specific preparation will be added without pretending they are live today.</p><Link href="/ats-scan" className={`${primary} mt-8`}>Start with live tools</Link></div></section>
  </main><footer className="border-t border-line-light bg-surface-2-light"><div className="mx-auto flex max-w-[1280px] flex-col gap-5 px-5 py-10 sm:px-8 lg:flex-row lg:items-center lg:justify-between lg:px-12"><div><p className="font-bold">GCC MENTOR</p><p className="mt-1 text-xs text-ink-400">Built for professionals targeting the Gulf job market.</p></div><div className="flex flex-wrap gap-4 text-sm font-semibold text-ink-700"><Link href="/ats-scan">Free CV Scan</Link><Link href="/onboarding">Get Started</Link><Link href="/login">Log in</Link><a href="#pricing">Start Free</a><a href="#resources">FAQ</a></div></div></footer></div>
}
